export const BRIDGE_HOST = '127.0.0.1';
export const BRIDGE_BOOTSTRAP_PORT = 45721;
export const BRIDGE_ENV_PORT_KEY = 'PI_IDE_BRIDGE_SERVER_PORT';
export const BRIDGE_ENV_AUTH_TOKEN_KEY = 'PI_IDE_BRIDGE_AUTH_TOKEN';
export const BRIDGE_BOOTSTRAP_AUTH_ENV_KEY = 'PI_IDE_BRIDGE_BOOTSTRAP_AUTH_TOKEN';
export const BRIDGE_OPEN_DIFF_PATH = '/openDiff';
export const BRIDGE_CLOSE_DIFF_PATH = '/closeDiff';
export const BRIDGE_HEALTH_PATH = '/health';
export const BRIDGE_CONTEXT_STREAM_PATH = '/context/stream';
export const BRIDGE_DIAGNOSTICS_PATH = '/diagnostics';
export const BRIDGE_BOOTSTRAP_INFO_PATH = '/bridgeInfo';
export const BRIDGE_BOOTSTRAP_RESOLVE_PATH = '/resolveBridgeForPi';

const bridgeContract = {
  BRIDGE_HOST,
  BRIDGE_BOOTSTRAP_PORT,
  BRIDGE_ENV_PORT_KEY,
  BRIDGE_ENV_AUTH_TOKEN_KEY,
  BRIDGE_BOOTSTRAP_AUTH_ENV_KEY,
  BRIDGE_OPEN_DIFF_PATH,
  BRIDGE_CLOSE_DIFF_PATH,
  BRIDGE_HEALTH_PATH,
  BRIDGE_CONTEXT_STREAM_PATH,
  BRIDGE_DIAGNOSTICS_PATH,
  BRIDGE_BOOTSTRAP_INFO_PATH,
  BRIDGE_BOOTSTRAP_RESOLVE_PATH,
} as const;

export default bridgeContract;
